// Package dto holds request/response types mirroring api/*/models.yaml field-for-field.
//
// These are hand-authored, NOT generated by oapi-codegen (BE-01 in
// 6-development/BE_IMPLEMENTATION_PLAN.md called for codegen, but no Go toolchain was
// available in the environment that wrote this code). Replace this package with generated
// code once a toolchain is available, to remove the risk of silent drift from the contract.
package dto

import "time"

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Client — auth/models.yaml#/components/schemas/Client. No password_hash field: it must
// never be serialized back to the API.
type Client struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type AuthResponse struct {
	Token  string `json:"token"`
	Client Client `json:"client"`
}

type Program struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Difficulty  string   `json:"difficulty"`
	PhotoURL    string   `json:"photo_url"`
	Ingredients []string `json:"ingredients"`
	Allergens   []string `json:"allergens"`
}

type Chef struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Slot struct {
	ID                 string    `json:"id"`
	Program            Program   `json:"program"`
	Chef               Chef      `json:"chef"`
	StartAt            time.Time `json:"start_at"`
	TotalSeats         int       `json:"total_seats"`
	FreeSeats          int       `json:"free_seats"`
	Price              int       `json:"price"`
	Status             string    `json:"status"`
	CancellationReason *string   `json:"cancellation_reason,omitempty"`
}

type SlotListResponse struct {
	Items []Slot `json:"items"`
}

// Error — common/models.yaml#/components/schemas/Error.
type Error struct {
	Code    string         `json:"code"`
	Message string         `json:"message"`
	Details map[string]any `json:"details,omitempty"`
}
